### ISSUE TITLE
1,327 downloads in the last day

### ISSUE THREAD

**Issue by parkerault** [iandotkelly/aws-cli#2]
I'm trying to figure out why there are so many daily installs of this package when it appears to be an abandoned project. It's concerning if people are mistakenly installing this thinking it is the official AWS CLI client.

**Comment by iandotkelly** [comment]
Thanks.  I had no idea there were so many downloads.    This was not my intention.  I intended to write a wrapper for the AWS CLI then some decent official tools came out. 

What do you suggest? - I'm concerned that someone somewhere actually uses the one function that it does provide and that unpublishing it would impact them.  Anyone looking at the npm or github page should be able to see that its not official and does very little.

**Comment by iandotkelly** [comment]
Perhaps I should leave a note in the readme directing people to the official AWS code.

**Comment by parkerault** [comment]
Maybe you should contact npm or aws about it so someone with worse intentions doesn't claim it. I sent an email to npm and they didn't seem to be the least bit concerned about it, which is pretty damning. You could try emailing `aws-security@amazon.com` and explain the situation and that you'd like to transfer ownership of the package. Thanks for doing the right thing :).

**Comment by iandotkelly** [comment]
I can try, but I doubt I'll get any traction from that route - its not a malicious module, it does actually support the one AWS command I needed when I started it. The downloads are just because its a similar name to the official `awscli` module

At the very least I can mark it as deprecated and put a clear note at the top of the readme with links to the official cli.

Thanks for taking the time to contact me.
